# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.provider :virtualbox do |v|
    v.name = "servflask"
    v.memory = 512
    v.cpus = 2
    # optimizing HTTP requests by enable NAT hosts DNS resolver
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 5000, host: 5000    
    
  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :servflask do |servflask|
  end

    config.vm.provision "file", source: "../Flask", destination: "HelloWorld"
    
  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../Ansible/provisioning/playbook.yml"
    ansible.host_key_checking = false
    ansible.verbose = "vv"
    ansible.sudo = true
  end
end
